import { ImageResponse } from "next/og";
import { bracketBars } from "./apple-icon";

// Social card for links to the site. The GitHub social preview is a different
// aspect ratio and is generated by scripts/render-brand.mjs, because GitHub has
// no API for that upload.
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";
export const alt = "Headless — browser control for agents";

const ARM = 74;
const THICKNESS = 11;
const FRAME = 168;

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          width: "100%",
          height: "100%",
          padding: 80,
          backgroundImage: "linear-gradient(160deg, #1c1c24, #050508)",
          color: "#f5f5f2",
        }}
      >
        <div style={{ display: "flex", position: "relative", width: FRAME, height: FRAME }}>
          {bracketBars(ARM, THICKNESS).map((style, index) => (
            <div key={index} style={style} />
          ))}
        </div>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", fontSize: 74, letterSpacing: -2 }}>headless</div>
          <div style={{ display: "flex", fontSize: 34, color: "#a5a5ad", marginTop: 16 }}>
            Give your agent a real browser.
          </div>
          <div style={{ display: "flex", fontSize: 26, color: "#7a7a86", marginTop: 28 }}>
            Semantic commands, not screen coordinates. macOS and Linux.
          </div>
        </div>
      </div>
    ),
    size,
  );
}
